spring:
  profiles:
    active:
      - dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10 # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      min-idle: 10 # 最小连接池数量
      maxActive: 200 # 最大连接池数量
      maxWait: 60000 # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置
      timeBetweenEvictionRunsMillis: 60000 # 关闭空闲连接的检测时间间隔.Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
      minEvictableIdleTimeMillis: 300000 # 连接的最小生存时间.连接保持空闲而不被驱逐的最小时间
      validationQuery: SELECT 1 FROM DUAL # 验证数据库服务可用性的sql.用来检测连接是否有效的sql 因数据库方言而差, 例如 oracle 应该写成 SELECT 1 FROM DUAL
      testWhileIdle: true # 申请连接时检测空闲时间，根据空闲时间再检测连接是否有效.建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRun
      testOnBorrow: false # 申请连接时直接检测连接是否有效.申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false # 归还连接时检测连接是否有效.归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      poolPreparedStatements: true # 开启PSCache
      maxPoolPreparedStatementPerConnectionSize: 20 #设置PSCache值
      connectionErrorRetryAttempts: 3 # 连接出错后再尝试连接三次
      breakAfterAcquireFailure: true # 数据库服务宕机自动重连机制
      timeBetweenConnectErrorMillis: 300000 # 连接出错后重试时间间隔
      asyncInit: true # 异步初始化策略
      remove-abandoned: true # 是否自动回收超时连接
      remove-abandoned-timeout: 1800 # 超时时间(以秒数为单位)
      transaction-query-timeout: 6000 # 事务超时时间
      filters: stat,wall,log4j2
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        allow:
        deny:
        reset-enable: false
        login-username: admin
        login-password: wy1wj2yj3!@#
  application:
    name: user-service
  devtools:
    livereload:
      port: 35738
    restart:
      enabled: true
      additional-paths: src/main/java, src/main/resources
  servlet:
    multipart:
      enabled: true
      #限制单个文件的最大值
      max-file-size: 10MB
      #限制上传的多个文件的总大小
      max-request-size: 50MB
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  servlet:
    context-path: /find
  port: 8081
  tomcat:
    accept-count: 500 # Maximum queue length for incoming connection requests when all possible request processing threads are in use.
    accesslog.buffered: true # Whether to buffer output such that it is flushed only periodically.
    accesslog.directory: logs # Directory in which log files are created. Can be absolute or relative to the Tomcat base dir.
    accesslog.enabled: true # Enable access log.
    accesslog.file-date-format: .yyyy-MM-dd # Date format to place in the log file name.
    accesslog.pattern: common # Format pattern for access logs.
    accesslog.prefix: access_log # Log file name prefix.
    accesslog.rename-on-rotate: false # Whether to defer inclusion of the date stamp in the file name until rotate time.
    accesslog.request-attributes-enabled: false # Set request attributes for the IP address, Hostname, protocol, and port used for the request.
    accesslog.rotate: true # Whether to enable access log rotation.
    accesslog.suffix: .log # Log file name suffix.
    background-processor-delay: 10 # Delay between the invocation of backgroundProcess methods. If a duration suffix is not specified, seconds will be used.
    basedir: catalina_find_user_${server.port} # Tomcat base directory. If not specified, a temporary directory is used.
    internal-proxies: 10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|\\192\\.168\\.\\d{1,3}\\.\\d{1,3}|\\169\\.254\\.\\d{1,3}\\.\\d{1,3}|\\127\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|\\172\\.1[6-9]{1}\\.\\d{1,3}\\.\\d{1,3}|\\172\\.2[0-9]{1}\\.\\d{1,3}\\.\\d{1,3}|\\172\\.3[0-1]{1}\\.\\d{1,3}\\.\\d{1,3}\\0:0:0:0:0:0:0:1\\::1 # Regular expression that matches proxies that are to be trusted.
    max-connections: 2000 # Maximum number of connections that the server accepts and processes at any given time.
    max-http-post-size: 2048 # M                                                                                                                                                                        aximum size of the HTTP post content.
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 100 # Minimum amount of worker threads.
    port-header: X-Forwarded-Port # Name of the HTTP header used to override the original port value.
    protocol-header: X-Forwarded-Proto # Header that holds the incoming protocol, usually named "X-Forwarded-Proto".
    redirect-context-root: true # Whether requests to the context root should be redirected by appending a / to the path.
    remote-ip-header: X-FORWARDED-FOR # Name of the HTTP header from which the remote IP is extracted. For instance, `X-FORWARDED-FOR`.
    resource.cache-ttl: 200 # Time-to-live of the static resource cache.
    uri-encoding: UTF-8 # Character encoding to use to decode the URI.
#百度IP定位接口参数配置
baidu:
  url: https://api.map.baidu.com/location/ip
  ak: OvTyDm7rLM2soYix1D0tZKEs4SL0GlAx
#阿里云IP定位接口参数配置
aliyun:
  appcode: 5c21289ddc9749f6a105b40d24479398
  url: http://iploc.market.alicloudapi.com/v3/ip
#########项目路径参数配置#########
project-url:
  project-name: /find
  res-app-img: /img/app/
  res-head-icon: /img/head/
  res-background-icon: /img/background/
  res-voices-file: /res/voices/
  res-images-file: /res/images/
  default-head-icon: head.png
  default-bg-icon: bg.png
  default-male-content: 新人小生，初来乍到，请多关照。
  default-female-content: 新人妹子，初来乍到，请多关照。
  res-app-product-img: /img/app/product/
#########ribbon客户端配置##########
ribbon:
  http:
    client:
      enabled: true
  okhttp:
    enabled: true
  restclient:
    enabled: true
##########feign客户端配置##########
feign:
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml
        - application/xml
        - application/json
        - multipart/form-data
    response:
      enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: FULL
  okhttp:
    enabled: true
#########Mybatis自身配置##########
mybatis:
  configuration:
    #驼峰命名规范，如：数据库字段是order_id那么实体字段就要写成orderId
    map-underscore-to-camel-case: true
  type-aliases-package: com.potato369.find.mbg.model
  mapper-locations:
    - classpath:com/potato369/find/mbg/mapper/*Mapper.xml
pagehelper:
  support-methods-arguments: true
  reasonable: false
  helper-dialect: mysql
logging:
  level:
    org:
      springframework:
        web: TRACE
        cloud:
          netflix: TRACE