logging:
  config: classpath:logback-spring-dev.xml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 8.135.36.45:8848
        namespace: bb0e196a-546f-48b8-af0f-ae445d63c0cd
  servlet:
    multipart:
      location: ~/temp/
  datasource:
    url: jdbc:mysql://potato369.com:31306/find_dev_test02?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: find
    password: XueGod!@#123
#########项目相关配置#########
project-url:
  domain: http://127.0.0.1:8081             #项目网关域名前缀
  upload-res: /usr/local/var/www/Resources  #资源文件存放nginx服务器路径
  res-domain: http://127.0.0.1:8000         #Nginx服务器路径网关域名