logging:
  config: classpath:logback-spring-dev.xml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.31:8848
        namespace: 174f115e-55dd-486a-90e8-a96fe1a63965
  servlet:
     multipart:
        location: D://temp//
  datasource:
    url: jdbc:mysql://192.168.31.31:3306/find_dev_test01?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: find
    password: XueGod!@#123
#########项目相关配置#########
project-url:
  domain: http://192.168.31.31:8081     #项目网关域名前缀
  upload-res: D:/Program/Resources      #资源文件存放nginx服务器路径
  res-domain: http://192.168.31.31:9000 #Nginx服务器路径网关域名