logging:
  config: classpath:logback-spring-prod.xml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 6e2d06b6-0a8b-4a0c-a306-78fc564aeb8b
  servlet:
   multipart:
     location: ~/temp/        
  datasource:
    url: jdbc:mysql://potato369.com:31306/find_dev_test01?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: find
    password: XueGod!@#123
#项目相关配置
project-url:
  domain: http://8.135.36.45:8081             #项目网关域名前缀
  upload-res: /data/Resources                 #资源文件存放nginx服务器路径
  res-domain: http://8.135.36.45:8000         #Nginx服务器路径网关域名