logging:
  config: classpath:logback-spring-prod.xml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 6e2d06b6-0a8b-4a0c-a306-78fc564aeb8b
  datasource:
    druid:
      username: find                                          #数据库连接用户名
      password: XueGod!@#123                                  #数据库连接密码
      url: jdbc:mysql://potato369.com:31306/find_dev_test01?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true  #数据库连接URL 
      initial-size: 5                                         #数据库初始化连接大小
      min-idle: 12                                            #数据库最小连接池数量
      max-active: 50                                          #数据库最大连接池数量        