spring:
  profiles:
    active:
      - dev3
  application:
    name: portal-service
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
  devtools:
    livereload:
      port: 35737
    restart:
      enabled: true
      additional-paths: src/main/java, src/main/resources
  servlet:
    multipart:
      enabled: true
      #限制单个文件的最大值
      max-file-size: 10MB
      #限制上传的多个文件的总大小
      max-request-size: 50MB
server:
  servlet:
    context-path: /find
  port: 8084
  tomcat:
    accept-count: 500 # Maximum queue length for incoming connection requests when all possible request processing threads are in use.
    accesslog.buffered: true # Whether to buffer output such that it is flushed only periodically.
    accesslog.directory: logs # Directory in which log files are created. Can be absolute or relative to the Tomcat base dir.
    accesslog.enabled: true # Enable access log.
    accesslog.file-date-format: .yyyy-MM-dd # Date format to place in the log file name.
    accesslog.pattern: common # Format pattern for access logs.
    accesslog.prefix: access_log # Log file name prefix.
    accesslog.rename-on-rotate: false # Whether to defer inclusion of the date stamp in the file name until rotate time.
    accesslog.request-attributes-enabled: false # Set request attributes for the IP address, Hostname, protocol, and port used for the request.
    accesslog.rotate: true # Whether to enable access log rotation.
    accesslog.suffix: .log # Log file name suffix.
    background-processor-delay: 10 # Delay between the invocation of backgroundProcess methods. If a duration suffix is not specified, seconds will be used.
    basedir: catalina_find_portal_${server.port} # Tomcat base directory. If not specified, a temporary directory is used.
    internal-proxies: 10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|\\192\\.168\\.\\d{1,3}\\.\\d{1,3}|\\169\\.254\\.\\d{1,3}\\.\\d{1,3}|\\127\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|\\172\\.1[6-9]{1}\\.\\d{1,3}\\.\\d{1,3}|\\172\\.2[0-9]{1}\\.\\d{1,3}\\.\\d{1,3}|\\172\\.3[0-1]{1}\\.\\d{1,3}\\.\\d{1,3}\\0:0:0:0:0:0:0:1\\::1 # Regular expression that matches proxies that are to be trusted.
    max-connections: 2000 # Maximum number of connections that the server accepts and processes at any given time.
    max-http-post-size: 2048 # M                                                                                                                                                                        aximum size of the HTTP post content.
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 100 # Minimum amount of worker threads.
    port-header: X-Forwarded-Port # Name of the HTTP header used to override the original port value.
    protocol-header: X-Forwarded-Proto # Header that holds the incoming protocol, usually named "X-Forwarded-Proto".
    redirect-context-root: true # Whether requests to the context root should be redirected by appending a / to the path.
    remote-ip-header: X-FORWARDED-FOR # Name of the HTTP header from which the remote IP is extracted. For instance, `X-FORWARDED-FOR`.
    resource.cache-ttl: 200 # Time-to-live of the static resource cache.
    uri-encoding: UTF-8 # Character encoding to use to decode the URI.
#########ribbon客户端配置##########
ribbon:
  http:
    client:
      enabled: true
  okhttp:
    enabled: true
  restclient:
    enabled: true
##########feign客户端配置##########
feign:
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml
        - application/xml
        - application/json
        - multipart/form-data
    response:
      enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: FULL
  okhttp:
    enabled: true
logging:
  level:
    org:
      springframework:
        web: TRACE
        cloud:
          netflix: TRACE          
  