spring:
  profiles:
    active:
      - dev2
  datasource:
    druid:
      async-init: true                                        #有initialSize数量较多时，打开会加快应用启动时间
      driver-class-name: com.mysql.cj.jdbc.Driver             #数据库连接驱动类名称
      keep-alive: true                                        #保持连接状态
      max-wait: 30000                                         #获取连接时最大等待时间，单位毫秒
      time-between-log-stats-millis: 30000                    #DruidDataSource有一个属性timeBetweenLogStatsMillis，配置timeBetweenLogStatsMillis>0之后，DruidDataSource会定期把监控数据输出到日志中
      time-between-eviction-runs-millis: 60000                #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 30000                   #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT NOW() FROM DUAL                #测试数据库连接SQL
      test-while-idle: true                                   #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-on-borrow: false                                   #获取连接时执行检测，建议关闭，影响性能
      test-on-return: false                                   #归还连接时执行检测，建议关闭，影响性能
      pool-prepared-statements: false                         #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      max-pool-prepared-statement-per-connection-size: 20     #开启poolPreparedStatements后生效
      filters: stat, wall                                     #配置扩展插件，常用的插件有=>stat：监控统计，log4j：打印log4j日志，wall：防御sql注入
      connection-properties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'  #通过connectProperties属性来打开mergeSql功能;慢SQL记录
      reset-stat-enable: true                                 #是否可以重置数据
      stat-view-servlet: #配置 Druid 监控信息显示页面，Druid内置提供了一个StatViewServlet用于展示Druid的统计信息，这个StatViewServlet的用途包括：1、提供监控信息展示的html页面 2、提供监控信息的JSON API，注意：使用StatViewServlet，建议使用druid 0.2.6以上版本。
        reset-enable: true                                    #允许清空统计数据
        login-username: admin                                 #为Druid监控配置访问监控信息有访问权限的用户名
        login-password: wy1wj2yj3!@#                          #为Druid监控配置访问监控信息有访问权限的密码
      remove-abandoned: true                                  #自动强制回收连接
      remove-abandoned-timeout-millis: 3000                   #超时时间（单位秒）      
  application:
    name: portal-service
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
  devtools:
    livereload:
      port: 35737
    restart:
      enabled: true
      additional-paths: src/main/java, src/main/resources
  servlet:
    multipart:
      enabled: true
      #限制单个文件的最大值
      max-file-size: 10MB
      #限制上传的多个文件的总大小
      max-request-size: 50MB
server:
  servlet:
    context-path: /find
  port: 8084
  tomcat:
    accept-count: 500 # Maximum queue length for incoming connection requests when all possible request processing threads are in use.
    accesslog.buffered: true # Whether to buffer output such that it is flushed only periodically.
    accesslog.directory: logs # Directory in which log files are created. Can be absolute or relative to the Tomcat base dir.
    accesslog.enabled: true # Enable access log.
    accesslog.file-date-format: .yyyy-MM-dd # Date format to place in the log file name.
    accesslog.pattern: common # Format pattern for access logs.
    accesslog.prefix: access_log # Log file name prefix.
    accesslog.rename-on-rotate: false # Whether to defer inclusion of the date stamp in the file name until rotate time.
    accesslog.request-attributes-enabled: false # Set request attributes for the IP address, Hostname, protocol, and port used for the request.
    accesslog.rotate: true # Whether to enable access log rotation.
    accesslog.suffix: .log # Log file name suffix.
    background-processor-delay: 10 # Delay between the invocation of backgroundProcess methods. If a duration suffix is not specified, seconds will be used.
    basedir: catalina_find_portal_${server.port} # Tomcat base directory. If not specified, a temporary directory is used.
    internal-proxies: 10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|\\192\\.168\\.\\d{1,3}\\.\\d{1,3}|\\169\\.254\\.\\d{1,3}\\.\\d{1,3}|\\127\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|\\172\\.1[6-9]{1}\\.\\d{1,3}\\.\\d{1,3}|\\172\\.2[0-9]{1}\\.\\d{1,3}\\.\\d{1,3}|\\172\\.3[0-1]{1}\\.\\d{1,3}\\.\\d{1,3}\\0:0:0:0:0:0:0:1\\::1 # Regular expression that matches proxies that are to be trusted.
    max-connections: 2000 # Maximum number of connections that the server accepts and processes at any given time.
    max-http-post-size: 2048 # M                                                                                                                                                                        aximum size of the HTTP post content.
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 100 # Minimum amount of worker threads.
    port-header: X-Forwarded-Port # Name of the HTTP header used to override the original port value.
    protocol-header: X-Forwarded-Proto # Header that holds the incoming protocol, usually named "X-Forwarded-Proto".
    redirect-context-root: true # Whether requests to the context root should be redirected by appending a / to the path.
    remote-ip-header: X-FORWARDED-FOR # Name of the HTTP header from which the remote IP is extracted. For instance, `X-FORWARDED-FOR`.
    resource.cache-ttl: 200 # Time-to-live of the static resource cache.
    uri-encoding: UTF-8 # Character encoding to use to decode the URI.
#########ribbon客户端配置##########
ribbon:
  http:
    client:
      enabled: true
  okhttp:
    enabled: true
  restclient:
    enabled: true
##########feign客户端配置##########
feign:
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml
        - application/xml
        - application/json
        - multipart/form-data
    response:
      enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: FULL
  okhttp:
    enabled: true
logging:
  level:
    org:
      springframework:
        web: TRACE
        cloud:
          netflix: TRACE          
  