spring:
  profiles:
    active:
      - dev1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10 # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      min-idle: 10 # 最小连接池数量
      maxActive: 200 # 最大连接池数量
      maxWait: 60000 # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置
      timeBetweenEvictionRunsMillis: 60000 # 关闭空闲连接的检测时间间隔.Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
      minEvictableIdleTimeMillis: 300000 # 连接的最小生存时间.连接保持空闲而不被驱逐的最小时间
      validationQuery: SELECT 1 FROM DUAL # 验证数据库服务可用性的sql.用来检测连接是否有效的sql 因数据库方言而差, 例如 oracle 应该写成 SELECT 1 FROM DUAL
      testWhileIdle: true # 申请连接时检测空闲时间，根据空闲时间再检测连接是否有效.建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRun
      testOnBorrow: false # 申请连接时直接检测连接是否有效.申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false # 归还连接时检测连接是否有效.归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      poolPreparedStatements: true # 开启PSCache
      maxPoolPreparedStatementPerConnectionSize: 20 #设置PSCache值
      connectionErrorRetryAttempts: 3 # 连接出错后再尝试连接三次
      breakAfterAcquireFailure: true # 数据库服务宕机自动重连机制
      timeBetweenConnectErrorMillis: 300000 # 连接出错后重试时间间隔
      asyncInit: true # 异步初始化策略
      remove-abandoned: true # 是否自动回收超时连接
      remove-abandoned-timeout: 1800 # 超时时间(以秒数为单位)
      transaction-query-timeout: 6000 # 事务超时时间
      filters: stat,wall,log4j2
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        allow:
        deny:
        reset-enable: false
        login-username: admin
        login-password: wy1wj2yj3!@#
  application:
    name: message-service
#  devtools:
#    livereload:
#      port: 35735
#    restart:
#      enabled: true
#      additional-paths: src/main/java, src/main/resources
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  servlet:
    context-path: /find
  port: 8082
#########Mybatis自身配置##########
mybatis:
  configuration:
    #驼峰命名规范，如：数据库字段是order_id那么实体字段就要写成orderId
    map-underscore-to-camel-case: true
  type-aliases-package: com.potato369.find.mbg.model
  mapper-locations:
    - classpath:com/potato369/find/mbg/mapper/*Mapper.xml
pagehelper:
  support-methods-arguments: true
  reasonable: false
  helper-dialect: mysql
#########集成极光推送配置#########
jpush:
  #AppKey为极光平台应用的唯一标识
  app-key: 2ca10b44a1a6a77c278cbf0a
  #用于服务器端API调用时与AppKey配合使用达到鉴权的目的，请保管好Master Secret防止外泄
  master-secret: c165704661401d94f6c7a7d8
  #离线消息保留时长(秒)
  live-time: 86400
  #一次推送最大数量(极光限制1000)
  max-size: 800
  #是否生产环境，true表示生产环境，false表示不是生产环境
  apns-production: false
#########项目路径参数配置#########
project-url:
  project-name: /find
  res-app-img: /img/app/
  res-head-icon: /img/head/
  res-background-icon: /img/background/
  res-voices-file: /res/voices/
  res-images-file: /res/images/
  default-head-icon: head.png
  default-bg-icon: bg.png
  default-male-content: 新人小生，初来乍到，请多关照。
  default-female-content: 新人妹子，初来乍到，请多关照。
  res-app-product-img: /img/app/product/             