spring:
  profiles:
    active:
    - dev
  datasource:
    druid:
      async-init: true                                        #有initialSize数量较多时，打开会加快应用启动时间
      driver-class-name: com.mysql.cj.jdbc.Driver             #数据库连接驱动类名称
      keep-alive: true                                        #保持连接状态
      max-wait: 30000                                         #获取连接时最大等待时间，单位毫秒
      time-between-log-stats-millis: 30000                    #DruidDataSource有一个属性timeBetweenLogStatsMillis，配置timeBetweenLogStatsMillis>0之后，DruidDataSource会定期把监控数据输出到日志中
      time-between-eviction-runs-millis: 60000                #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 30000                   #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT NOW() FROM DUAL                #测试数据库连接SQL
      test-while-idle: true                                   #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-on-borrow: false                                   #获取连接时执行检测，建议关闭，影响性能
      test-on-return: false                                   #归还连接时执行检测，建议关闭，影响性能
      pool-prepared-statements: false                         #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      max-pool-prepared-statement-per-connection-size: 20     #开启poolPreparedStatements后生效
      filters: stat, wall                                     #配置扩展插件，常用的插件有=>stat：监控统计，log4j：打印log4j日志，wall：防御sql注入
      connection-properties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'  #通过connectProperties属性来打开mergeSql功能;慢SQL记录
      reset-stat-enable: true                                 #是否可以重置数据
      stat-view-servlet: #配置 Druid 监控信息显示页面，Druid内置提供了一个StatViewServlet用于展示Druid的统计信息，这个StatViewServlet的用途包括：1、提供监控信息展示的html页面 2、提供监控信息的JSON API，注意：使用StatViewServlet，建议使用druid 0.2.6以上版本。
        reset-enable: true                                    #允许清空统计数据
        login-username: admin                                 #为Druid监控配置访问监控信息有访问权限的用户名
        login-password: wy1wj2yj3!@#                          #为Druid监控配置访问监控信息有访问权限的密码
      remove-abandoned: true                                  #自动强制回收连接
      remove-abandoned-timeout-millis: 3000                   #超时时间（单位秒）        
  application:
    name: message-service
  devtools:
    livereload:
      port: 35735
    restart:
      enabled: true
      additional-paths: src/main/java, src/main/resources
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  servlet:
    context-path: /find
  port: 8082
#########Mybatis自身配置##########
mybatis:
  configuration:
    #驼峰命名规范，如：数据库字段是order_id那么实体字段就要写成orderId
    map-underscore-to-camel-case: true
  type-aliases-package: com.potato369.find.mbg.model
  mapper-locations:
  -  classpath:com/potato369/find/mbg/mapper/*Mapper.xml
pagehelper:
  support-methods-arguments: true
  reasonable: false
  helper-dialect: mysql
#########集成极光推送配置#########
jpush:
  #AppKey为极光平台应用的唯一标识
  app-key: 2ca10b44a1a6a77c278cbf0a
  #用于服务器端API调用时与AppKey配合使用达到鉴权的目的，请保管好Master Secret防止外泄
  master-secret: c165704661401d94f6c7a7d8
  #离线消息保留时长(秒)
  live-time: 86400
  #一次推送最大数量(极光限制1000)
  max-size: 800
  #是否生产环境，true表示生产环境，false表示不是生产环境
  apns-production: false
#########项目路径参数配置#########
project-url:
  project-name: /find
  res-app-img: /img/app/
  res-head-icon: /img/head/
  res-background-icon: /img/background/
  res-voices-file: /res/voices/
  res-images-file: /res/images/
  default-head-icon: head.png
  default-bg-icon: bg.png
  default-male-content: 新人小生，初来乍到，请多关照。
  default-female-content: 新人妹子，初来乍到，请多关照。
  res-app-product-img: /img/app/product/             