logging:
  config: classpath:logback-spring-dev.xml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 8.135.36.45:8848
        namespace: bb0e196a-546f-48b8-af0f-ae445d63c0ad
  datasource:
    url: jdbc:mysql://192.168.31.31:3306/find_dev_test01?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: find
    password: XueGod!@#123
#项目相关配置
project-url:
  domain: http://192.168.31.31:8083       #项目网关域名前缀
  upload-res: D:/Program/Resources        #资源文件上传存放服务器路径
  res-domain: http://192.168.31.31:9000   #Nginx服务器路径网关域名

#集成极光推送配置
jpush:
  #AppKey为极光平台应用的唯一标识
  app-key: 2ca10b44a1a6a77c278cbf0a
  #用于服务器端API调用时与AppKey配合使用达到鉴权的目的，请保管好Master Secret防止外泄
  master-secret: c165704661401d94f6c7a7d8
  #离线消息保留时长(秒)
  live-time: 86400
  #一次推送最大数量(极光限制1000)
  max-size: 800
  #是否生产环境，true表示生产环境，false表示不是生产环境
  apns-production: false         