logging:
  config: classpath:logback-spring-prod.xml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 120.24.27.86:8848
        namespace: 6e2d06b6-0a8b-4a0c-a306-78fc564aeb8b
  servlet:
     multipart:
        location: ~/tmp/
  datasource:
    druid:
      url: jdbc:mysql://potato369.com:31306/find_dev_test01?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true  #数据库连接URL
      username: find                                          #数据库连接用户名
      password: XueGod!@#123                                  #数据库连接密码                
      initial-size: 5                                         #数据库初始化连接大小
      min-idle: 12                                            #数据库最小连接池数量
      max-active: 50                                          #数据库最大连接池数量
#项目相关配置
project-url: 
  domain: http://8.135.36.45:8083              #项目网关域名前缀
  upload-res: /data/Resources                  #资源文件上传存放服务器路径
  res-domain: http://8.135.36.45:8000          #Nginx服务器路径网关域名
#集成极光推送配置
jpush:
  #AppKey为极光平台应用的唯一标识
  app-key: 2ca10b44a1a6a77c278cbf0a
  #用于服务器端API调用时与AppKey配合使用达到鉴权的目的，请保管好Master Secret防止外泄
  master-secret: c165704661401d94f6c7a7d8
  #离线消息保留时长(秒)
  live-time: 86400
  #一次推送最大数量(极光限制1000)
  max-size: 800
  #是否生产环境，true表示生产环境，false表示不是生产环境
  apns-production: true   
          