spring:
  profiles:
    active:
      - dev2
  datasource:
    druid:
      async-init: true                                        #有initialSize数量较多时，打开会加快应用启动时间
      driver-class-name: com.mysql.cj.jdbc.Driver             #数据库连接驱动类名称
      keep-alive: true                                        #保持连接状态
      max-wait: 30000                                         #获取连接时最大等待时间，单位毫秒
      time-between-log-stats-millis: 30000                    #DruidDataSource有一个属性timeBetweenLogStatsMillis，配置timeBetweenLogStatsMillis>0之后，DruidDataSource会定期把监控数据输出到日志中
      time-between-eviction-runs-millis: 60000                #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 30000                   #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT NOW() FROM DUAL                #测试数据库连接SQL
      test-while-idle: true                                   #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-on-borrow: false                                   #获取连接时执行检测，建议关闭，影响性能
      test-on-return: false                                   #归还连接时执行检测，建议关闭，影响性能
      pool-prepared-statements: false                         #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      max-pool-prepared-statement-per-connection-size: 20     #开启poolPreparedStatements后生效
      filters: stat, wall                                     #配置扩展插件，常用的插件有=>stat：监控统计，log4j：打印log4j日志，wall：防御sql注入
      connection-properties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'  #通过connectProperties属性来打开mergeSql功能;慢SQL记录
      reset-stat-enable: true                                 #是否可以重置数据
      stat-view-servlet: #配置 Druid 监控信息显示页面，Druid内置提供了一个StatViewServlet用于展示Druid的统计信息，这个StatViewServlet的用途包括：1、提供监控信息展示的html页面 2、提供监控信息的JSON API，注意：使用StatViewServlet，建议使用druid 0.2.6以上版本。
        reset-enable: true                                    #允许清空统计数据
        login-username: admin                                 #为Druid监控配置访问监控信息有访问权限的用户名
        login-password: wy1wj2yj3!@#                          #为Druid监控配置访问监控信息有访问权限的密码
      remove-abandoned: true                                  #自动强制回收连接
      remove-abandoned-timeout-millis: 18000                  #超时时间（单位秒）
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
  application:
    name: dynamic-service
  devtools:
    livereload:
      port: 35733
    restart:
      enabled: true
      additional-paths: src/main/java, src/main/resources
  servlet:
    multipart:
      enabled: true
      #限制单个文件的最大值
      max-file-size: 5MB
      #限制上传的多个文件的总大小
      max-request-size: 50MB
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  servlet:
    context-path: /find
  port: 8083
#########Mybatis自身配置##########
mybatis:
  configuration:
    #驼峰命名规范，如：数据库字段是order_id那么实体字段就要写成orderId
    map-underscore-to-camel-case: true
  type-aliases-package: com.potato369.find.mbg.model
  mapper-locations:
    - classpath:com/potato369/find/mbg/mapper/*Mapper.xml
pagehelper:
  support-methods-arguments: true
  reasonable: false
  helper-dialect: mysql
baidu:
  url: https://api.map.baidu.com/location/ip
  ak: OvTyDm7rLM2soYix1D0tZKEs4SL0GlAx
#项目路径参数配置
project-url:
  project-name: /find
  res-app-img: /img/app/
  res-head-icon: /img/head/
  res-background-icon: /img/background/
  res-voices-file: /res/voices/
  res-images-file: /res/images/
#动态筛选年龄范围配置
dynamic:
  age:
    default:
      min: 16
      max: 35
    range:
      min: 16
      max: 150
      timeAfterHour: 720
#feign客户端配置
feign:
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml
        - application/xml
        - application/json
        - multipart/form-data
    response:
      enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: FULL      