logging:
  config: classpath:logback-spring-test.xml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 8.135.36.45:8848
        namespace: ff16f08d-13a1-481f-a01c-fefc6d33cb74
  datasource:
    druid:
      username: root                                          #数据库连接用户名
      password: XueGod!@#123                                  #数据库连接密码
      url: jdbc:mysql://188.131.154.96:3306/find_dev_test01?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true  #数据库连接URL
      initial-size: 2                                         #数据库初始化连接大小
      min-idle: 5                                             #数据库最小连接池数量
      max-active: 8                                           #数据库最大连接池数量
              
#项目相关配置
project-url: 
  domain: http://188.131.154.96:8083        		 #项目网关域名前缀
  upload-res: /ebookData/upgrade_file/http/Resources #资源文件上传存放服务器路径
  res-domain: http://188.131.154.96:8000    		 #Nginx服务器路径网关域
#集成极光推送配置
jpush:
  #AppKey为极光平台应用的唯一标识
  app-key: 2ca10b44a1a6a77c278cbf0a
  #用于服务器端API调用时与AppKey配合使用达到鉴权的目的，请保管好Master Secret防止外泄
  master-secret: c165704661401d94f6c7a7d8
  #离线消息保留时长(秒)
  live-time: 86400
  #一次推送最大数量(极光限制1000)
  max-size: 800
  #是否生产环境，true表示生产环境，false表示不是生产环境
  apns-production: false   