logging:
  config: classpath:logback-spring-prod.xml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 6e2d06b6-0a8b-4a0c-a306-78fc564aeb8b
  datasource:
    druid:
      url: jdbc:mysql://potato369.com:31306/find_dev_test01?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true  #数据库连接URL
      username: find                                          #数据库连接用户名
      password: XueGod!@#123                                  #数据库连接密码
      initial-size: 2                                         #数据库初始化连接大小
      min-idle: 5                                             #数据库最小连接池数量
      max-active: 20                                          #数据库最大连接池数量
#项目相关配置
project-url: 
  domain: http://8.135.36.45:8083              #项目网关域名前缀
  upload-res: /data/Resources                  #资源文件上传存放服务器路径
  res-domain: http://8.135.36.45:8000          #Nginx服务器路径网关域名      