logging:
  config: classpath:logback-spring-dev.xml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 8.135.36.45:8848
        namespace: bb0e196a-546f-48b8-af0f-ae445d63c0ad
  datasource:
    url: jdbc:mysql://192.168.31.38:3306/find_dev_test02?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true  #数据库连接URL
    username: find02                                        #数据库连接用户名
    password: XueGod!@#123                                  #数据库连接密码
#项目相关配置
project-url:
  domain: http://192.168.31.38:8085   #项目网关域名前缀
  upload-res: D:/Program/Resources    #资源文件上传存放服务器路径
  res-domain: http://192.168.31.38:9000 #Nginx服务器路径网关域名