logging:
  config: classpath:logback-spring-dev.xml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 120.24.27.86:8848
        namespace: 9aa3d18e-da31-4590-9891-ce8d2104440a
  datasource:
    druid:
      url: jdbc:mysql://potato369.com:31306/find_dev_test01?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true  #数据库连接URL
      username: find                                          #数据库连接用户名
      password: XueGod!@#123                                  #数据库连接密码
      initial-size: 2                                         #数据库初始化连接大小
      min-idle: 5                                             #数据库最小连接池数量
      max-active: 20                                          #数据库最大连接池数量        
#项目相关配置
project-url: 
  domain: http://192.168.3.4:8083               #项目网关域名前缀
  upload-res: /usr/local/var/www/Resources      #资源文件上传存放服务器路径
  res-domain: http://192.168.3.4:9001           #Nginx服务器路径网关域名      