logging:
  config: classpath:logback-spring-test.xml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 8.135.36.45:8848
        namespace: ff16f08d-13a1-481f-a01c-fefc6d33cb74
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/find_dev_test01?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true  #数据库连接URL
    username: find                                          #数据库连接用户名
    password: XueGod!@#123                                  #数据库连接密码
#项目相关配置
project-url:
  domain: http://188.131.154.96:8000   #Nginx服务器路径网关域名      