logging:
  config: classpath:logback-spring-dev.xml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 8.135.36.45:8848
        namespace: bb0e196a-546f-48b8-af0f-ae445d63c0cd
  datasource:
    url: jdbc:mysql://192.168.3.84:3306/find_dev_test01?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: find
    password: XueGod!@#123
#项目相关配置
project-url:
  domain: http://192.168.3.84:8000   #Nginx服务器路径网关域名